name: Waka Readme

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest

    steps:
      - name: Update README with WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
